version: '3'
services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    volumes:
      - ./website:/website
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      NGINX_LOG_LEVEL: DEBUG
